{% set name = "goes2go" %}
{% set version = "2024.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cef2b7d22e4643d7ed3c27c2faa4f5cc96380835d208b6d9c7b8b1c42a3cbeb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONIOENCODING=utf8

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools_scm

  run:
    - cartopy
    - h5netcdf
    - metpy
    - netcdf4
    - numpy
    - pandas
    - python >=3.8
    - pygrib
    - s3fs
    - toml
    - xarray

test:
  commands:
    - pip check
  imports:
    - goes2go
  requires:
    - pip

about:
  home: https://github.com/blaylockbk/goes2go
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Retrieve GOES-East/West data from AWS. RGB recipes included!
  description: |
    GOES-East and GOES-West satellite data are made available on Amazon Web
    Services through NOAA's Big Data Program. `goes2go` is a python package
    that makes it easy to find and download the files you need to your local
    computer. Some additional helpers are provided that make working with GOES
    data easy and fun, such as recipes for RGB composites.
  doc_url: https://goes2go.readthedocs.io/
  dev_url: https://github.com/blaylockbk/goes2go

extra:
  recipe-maintainers:
    - blaylockbk
